kind: pipeline
name: default
workspace:
  base: github.com/llIllIllIlllIll/CloudNativePractice
steps:
  - name: testAndBuild
    image: openjdk,maven
    commands:
      - mvnw clean package
    when:
      branch:
      - tryDrone
      event:
      - push