kind: pipeline
name: default
steps:
  - name: testAndBuild
    image: openjdk
    image: maven
    commands:
      - mvnw clean package
    when:
      branch:
      - tryDrone
      event:
      - push