kind: pipeline
name: default
platfrom: 
  os: linux
  arch: amd64
steps:
  - name: test
    image: openjdk
    image: maven
    commands:
      - cd wordladder
      - mvn test
    when: 
      event: push
  - name: build
    image: openjdk
    image: maven
    commands:
      - cd wordladder
      - mvn clean package
    when:
      event: push

      